version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: banksystem
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
